/*=========================================================================
 *
 *  Copyright NumFOCUS
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         https://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/

#ifndef itkImpactModelConfiguration_h
#define itkImpactModelConfiguration_h

// Intentionally free of any LibTorch dependency so castxml can parse it and expose the
// class to Python (WrapITK). The TorchScript model and all other torch state live in an
// opaque ImpactModelConfigurationImpl, reached only from translation units that already depend
// on LibTorch via itkImpactModelConfigurationDetail.h.

// Impact_EXPORT marks ImpactModelConfiguration for export from the Impact shared library (Windows DLL
// declspec). ImpactExport.h is generated by ITK's module build, so it exists when this module is
// built normally; when the header is consumed standalone (e.g. Elastix compiles the backend
// sources directly via ITKIMPACT_INCLUDE_DIR, without the generated header) fall back to an
// empty macro -- no cross-DLL export is needed in that case.
#if defined(__has_include)
#  if __has_include("ImpactExport.h")
#    include "ImpactExport.h"
#  else
#    define Impact_EXPORT
#  endif
#else
#  include "ImpactExport.h"
#endif

#include <algorithm>
#include <cstdint>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

/**
 * ******************* GetStringFromVector ***********************
 */
template <typename T>
std::string
GetStringFromVector(const std::vector<T> & vec)
{
  std::stringstream ss;
  ss << "(";
  for (int i = 0; i < vec.size(); ++i)
  {
    ss << vec[i];
    if (i != vec.size() - 1)
    {
      ss << " ";
    }
  }
  ss << ")";
  return ss.str();
} // end GetStringFromVector

namespace itk
{
namespace detail
{
struct ImpactModelConfigurationImpl;
} // namespace detail

/**
 * Configuration for a TorchScript model used to extract semantic features.
 *
 * Holds the model path, input channel count, patch size, voxel size, overlap and the
 * per-layer mask, plus an opaque handle to the loaded TorchScript module. The public
 * interface uses only POD/STL types so the class is wrappable to Python; the LibTorch
 * module is reached through the accessors in itkImpactModelConfigurationDetail.h.
 */
struct Impact_EXPORT ImpactModelConfiguration
{
public:
  /** Load a TorchScript model and store its configuration. The model is loaded on the
   * CPU; move it with ModelTo() (itkImpactModelConfigurationDetail.h). */
  ImpactModelConfiguration(std::string               modelPath,
                     unsigned int              dimension,
                     unsigned int              numberOfChannels,
                     std::vector<unsigned int> patchSize,
                     std::vector<float>        voxelSize,
                     std::vector<unsigned int> overlap,
                     std::vector<bool>         layersMask,
                     bool                      useMixedPrecision);

  /** An empty configuration with no associated model. */
  ImpactModelConfiguration() = default;

  bool
  operator==(const ImpactModelConfiguration & rhs) const
  {
    return m_modelPath == rhs.m_modelPath && m_dimension == rhs.m_dimension &&
           m_numberOfChannels == rhs.m_numberOfChannels && m_patchSize == rhs.m_patchSize &&
           m_voxelSize == rhs.m_voxelSize && m_layersMask == rhs.m_layersMask;
  }

  friend std::ostream &
  operator<<(std::ostream & os, const ImpactModelConfiguration & config)
  {
    os << "\t\tPath : " << config.m_modelPath << "\n\t\tDimension : " << config.m_dimension
       << "\n\t\tNumberOfChannels : " << config.m_numberOfChannels
       << "\n\t\tPatchSize : " << GetStringFromVector<int64_t>(config.m_patchSize)
       << "\n\t\tVoxelSize : " << GetStringFromVector<float>(config.m_voxelSize)
       << "\n\t\tLayersMask : " << GetStringFromVector<bool>(config.m_layersMask);
    return os;
  }

  const std::string &
  GetModelPath() const
  {
    return m_modelPath;
  }
  unsigned int
  GetDimension() const
  {
    return m_dimension;
  }
  unsigned int
  GetNumberOfChannels() const
  {
    return m_numberOfChannels;
  }
  /** The patch the model was exported for, in ITK axis order (x, y, z) -- the order the voxel
   * size beside it is given in, and the one every consumer reads it in. A model of lower
   * dimension than the image declares only the axes it spans, the leading ITK ones. */
  const std::vector<int64_t> &
  GetPatchSize() const
  {
    return m_patchSize;
  }
  const std::vector<float> &
  GetVoxelSize() const
  {
    return m_voxelSize;
  }
  /** The patch overlap per axis, in voxels of the model's own grid, in ITK axis order (x, y, z)
   * like GetPatchSize() and GetVoxelSize().
   *
   * Always Dimension entries long: the constructor repeats the last entry it was given to fill
   * the missing axes, so a single value still means "the same on every axis". A per-axis
   * overlap is what an anisotropic patch needs -- a [96, 128, 160] network
   * asked for the same voxel overlap on all three axes blends its short axis over a much larger
   * fraction of the patch than its long one. */
  const std::vector<unsigned int> &
  GetOverlaps() const
  {
    return m_overlaps;
  }

  /** Override the per-axis overlap, in ITK axis order like GetPatchSize(). Fewer entries than
   * Dimension repeat the last one, so a single value still means "the same on every axis".
   * Ignored by a configuration that has no model, whose dimension is zero. */
  void
  SetOverlaps(const std::vector<unsigned int> & overlaps)
  {
    if (overlaps.empty() || m_dimension == 0)
    {
      return;
    }
    m_overlaps.assign(m_dimension, overlaps.back());
    for (unsigned int d = 0; d < m_dimension && d < overlaps.size(); ++d)
    {
      m_overlaps[d] = overlaps[d];
    }
  }

  /** The window overlapping patches are blended with, by name: one of
   *
   *  - `mean`     -- plain average of the patches covering a voxel;
   *  - `cosinus`  -- raised-cosine taper, an exact partition of unity over the overlap;
   *  - `gaussian` -- nnU-Net's importance weighting, so what TotalSegmentator and
   *                  MRSegmentator reassemble with (use it to reproduce their output);
   *  - `trim`     -- keep each patch's central band instead of averaging, which is what
   *                  carries a discrete output (a label map, an arg-max) through reassembly.
   *
   * Defaults to `cosinus`. */
  const std::string &
  GetPatchCombine() const
  {
    return m_patchCombine;
  }
  void
  SetPatchCombine(const std::string & patchCombine)
  {
    m_patchCombine = patchCombine;
  }

  const std::vector<bool> &
  GetLayersMask() const
  {
    return m_layersMask;
  }

  /** Precomputed physical patch offsets for the online (non-Static) inference: one inner
   * vector of length Dimension per patch voxel, holding (index - patchSize/2) * voxelSize
   * along each axis (x fastest). Filled by the constructor. POD only, so it stays
   * torch-free; the torch-side helpers live in itkImpactModelConfigurationDetail.h. */
  const std::vector<std::vector<float>> &
  GetPatchIndex() const
  {
    return m_patchIndex;
  }

  /** Opaque handle to the loaded TorchScript module and dtype; nullptr for a
   * default-constructed configuration. Prefer the accessors in
   * itkImpactModelConfigurationDetail.h; this pointer exists only to keep this header
   * free of LibTorch types. */
  detail::ImpactModelConfigurationImpl *
  GetImpl() const
  {
    return m_impl.get();
  }

private:
  std::string          m_modelPath;
  unsigned int         m_dimension{ 0 };
  unsigned int         m_numberOfChannels{ 0 };
  std::vector<int64_t> m_patchSize;
  std::vector<float>   m_voxelSize;
  // Per-axis overlap, and the window the overlapping patches are blended with. Both are
  // filled by the constructor from the scalar overlap, so a caller that knows nothing about
  // them (Elastix, which passes 0 and never blends) is unaffected.
  std::vector<unsigned int> m_overlaps;
  std::string               m_patchCombine{ "cosinus" };
  std::vector<bool>    m_layersMask;
  // Precomputed physical patch offsets (torch-free); see GetPatchIndex().
  std::vector<std::vector<float>> m_patchIndex;
  // shared_ptr keeps the special members usable with an incomplete impl type, so this
  // header needs no out-of-line destructor and stays torch-free.
  std::shared_ptr<detail::ImpactModelConfigurationImpl> m_impl;
};

/** How many of a model's layers are compared. Comparing several depths of the same network is
 * what LayersMask is for -- an early layer answers for texture, a late one for structure -- so
 * each kept layer gets its own feature map, its own loss and its own weight. This is the single
 * definition of that count: the metric sizes Distance, LayersWeight and SubsetFeatures by the
 * sum of it over the models, and ImageToFeaturesMap allocates one output per unit of it. */
inline unsigned int
NumberOfKeptLayers(const ImpactModelConfiguration & configuration)
{
  const std::vector<bool> & layersMask = configuration.GetLayersMask();
  return static_cast<unsigned int>(std::count(layersMask.begin(), layersMask.end(), true));
}

} // end namespace itk

#endif // end #ifndef itkImpactModelConfiguration_h
